### ISSUE TITLE
List children don't show on the correct parent

### ISSUE THREAD

**Issue by QuinnDamerell** [QuinnDamerell/UniversalMarkdown#10]
Try to render the content of this post (https://www.reddit.com/r/baconit/comments/4qlzdg/baconit_update_49_the_long_awaited_update/) and you will see that there should be 3 parent parts of the list with children under each, but what renders is all of the children under the first parent.

(thank again for your work btw)

**Comment by paulbartrum** [comment]
I'll take a look.  Hey, thanks for (finally) getting all my hard work out the door :-)

**Comment by paulbartrum** [comment]
Fixed!
