### ISSUE TITLE
Add an option to MarkdownTextBlock to make the text not selectable.

### ISSUE THREAD

**Issue by QuinnDamerell** [QuinnDamerell/UniversalMarkdown#4]
In the search results in Baconit I had to put a invisible overlay over the search results, otherwise when you tap them you select the text instead of going to the Subreddit. The down side of this is you can't tap links. 

It would be nice if there was an option on MarkdownTextBlock to disable text selection on the text boxes it renders inside it.

**Comment by paulbartrum** [comment]
There's already a property for this in XamlRenderer (it's called IsTextSelectionEnabled) -- I just need to hook it up to a DependencyProperty on MarkdownTextBlock.  Should be straightforward enough.

**Comment by paulbartrum** [comment]
Okay, I added IsTextSelectionEnabled.  While I was at it, I added about 40 other properties to enable customization of various margins, font sizes and colors.  Hope that helps :-)

**Comment by QuinnDamerell** [comment]
Awesome :)
