### ISSUE TITLE
Add support for multi-indent lists

### ISSUE THREAD

**Issue by QuinnDamerell** [QuinnDamerell/UniversalMarkdown#5]
I don't know if this is in the spec or not, but I think reddit supports mutli level indented list. I believe it is based off groups of 3 spaces before the element which causes the indent level to change.

**Comment by paulbartrum** [comment]
I've added full support for nested lists, including the ability to embed block elements like paragraphs and headers within list items.  Closing.

**Comment by QuinnDamerell** [comment]
Awesome. :)
