### ISSUE TITLE
Comment with italics crashes render

### ISSUE THREAD

**Issue by QuinnDamerell** [QuinnDamerell/UniversalMarkdown#6]
This comment will crash the render with an argument exception.

https://reddit.com/r/reallifedoodles/comments/41lmpg/ice_screams/cz3pl6g

**Comment by paulbartrum** [comment]
Superscript text uses a InlineUIContainer as a hacky way of rendering superscript.  Unfortunately, hyperlinks don't support InlineUIContainers so I've implemented an even more hacky workaround -- which works only if the entire hyperlink should be rendered as superscript (the common case).

**Comment by QuinnDamerell** [comment]
Awesome. After thinking about how to do super script that is all I could come up with also, so I was thinking you probably had to take the hacky way. Thanks for fixing this so quickly!

**Comment by paulbartrum** [comment]
No problem :-)
