### ISSUE TITLE
{high pri} New code refactor crashes Baconit when resizing the comment box.

### ISSUE THREAD

**Issue by QuinnDamerell** [QuinnDamerell/UniversalMarkdown#8]
@paulbartrum (I don't know what this tag does but I don't know if you see the notification otherwise)

I was debugging something in Baconit and finally figure out it was due to this refactor. What happens is when you take the comment box in Baconit, make it full screen, and then shrink it, the app crashes with and exception saying there is a layout loop.

Repo
1) Pull develop of universal markdown in the head of develop in Baconit.
2) Build
3) Open a subreddit
4) Open a post
5) Click the comment button
6) Toggle full screen on and off. (button on the far right of the comment box)
7) Global exception handler should be called.

I had to revert your new magic code out of develop of Baconit. I really need to get an update out so I couldn't delay for a fix. Let me know if you need any help debugging.

**Comment by paulbartrum** [comment]
Sorry about that, I'll take a look after work.

PS: No need for the `@paulbartrum` -- GitHub subscribed me to new issues when you made me a collaborator.

**Comment by paulbartrum** [comment]
The problem only occurs when the user hasn't entered any comment text, and appears to be triggered by the full screen button animating the height of the markdown preview textbox down to zero.  I'm guessing you weren't impacted previously because the old version of the markdown textbox was less scrupulous about ignoring whitespace so you always got at least a single line in the output.  I don't think this is a bug in the UniversalMarkdown project.

It appears you can work around the problem by modifying CommentBox.xaml:
```xml
<ScrollViewer x:Name="ui_livePreviewScroller"
              Style="{StaticResource ScrollViewerStyle}"
              VerticalScrollBarVisibility="Auto"
              ZoomMode="Disabled">
    <!--  the live preview box  -->
    <universalMarkdown:MarkdownTextBlock x:Name="ui_livePreviewBox"
                                         Margin="18,6,18,6"
                                         OnMarkdownLinkTapped="LivePreviewBox_OnMarkdownLinkTapped" />
</ScrollViewer>
```

changes to:
```xml
<ScrollViewer x:Name="ui_livePreviewScroller"
              Style="{StaticResource ScrollViewerStyle}"
              VerticalScrollBarVisibility="Auto"
              ZoomMode="Disabled"
              Padding="18,6,18,6">
    <!--  the live preview box  -->
    <universalMarkdown:MarkdownTextBlock x:Name="ui_livePreviewBox"
                                         OnMarkdownLinkTapped="LivePreviewBox_OnMarkdownLinkTapped" />
</ScrollViewer>
```

Don't ask me why that works!

The other option is you could set a MinHeight that is greater than zero (on the element and on the animations).  That should work too.

**Comment by QuinnDamerell** [comment]
Awesome! I actually didn't mean to say it was 100% a bug in the markdown, just that the changed caused it. I was also looing for a fix but I had another layout issue I was also looking at and didn't have much time. 

I hate these Layout cycle crashes. There is absolutely no way to debug them beyond randomly changing markdown until it is fixed. I created a bug on the XAML team telling them this an suggested they surface a stack trace or something. I hate not knowing what the actual problem is and fixing it with some "well this works, I don't know why" fix. :( But I had to the same for the comment box when it opens in flip view.

Anyways, thanks for the hard work. I'm going to try to put the new markdown code in the next update if we think it is ready. :)

**Comment by paulbartrum** [comment]
I totally agree that crashes without a stack trace are annoying, and crashes without an error message even more so.  This is the biggest problem with having a framework that is built on COM in my opinion: the chance you'll get an error with nothing but a HRESULT is substantially higher.

Regarding putting it in the next update: I'm happy if you are.  I haven't done a huge amount of testing, but the unit test coverage should mean it's reasonably stable.  I was thinking of downloading a couple hundred thousand comments (more?) and using them as a stress test.  As a bonus, it would probably make a pretty good benchmark.  What do you think?  Worth doing?

I also want to get nested lists and quotes working, which I think I'll get to in the next week or so.  You may want to wait for that (at which point you could plausibly claim to have complete markdown support).
